version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: paychase-mongo
    restart: unless-stopped
    ports:
      - "0.0.0.0:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data:/data/db
    networks:
      - paychase_net

  redis:
    image: redis:7
    container_name: paychase-redis
    restart: unless-stopped
    ports:
      - "0.0.0.0:6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - paychase_net

volumes:
  mongo_data:
  redis_data:

networks:
  paychase_net:
    external: true
